// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/v1/preview.proto

package previewv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePreviewRequest) Reset() {
	*x = CreatePreviewRequest{}
	mi := &file_api_v1_preview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePreviewRequest) ProtoMessage() {}

func (x *CreatePreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_preview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePreviewRequest.ProtoReflect.Descriptor instead.
func (*CreatePreviewRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_preview_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePreviewRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreatePreviewRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type DeletePreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePreviewRequest) Reset() {
	*x = DeletePreviewRequest{}
	mi := &file_api_v1_preview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePreviewRequest) ProtoMessage() {}

func (x *DeletePreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_preview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePreviewRequest.ProtoReflect.Descriptor instead.
func (*DeletePreviewRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_preview_proto_rawDescGZIP(), []int{1}
}

func (x *DeletePreviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Preview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastAccessAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_access_at,json=lastAccessAt,proto3" json:"last_access_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preview) Reset() {
	*x = Preview{}
	mi := &file_api_v1_preview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preview) ProtoMessage() {}

func (x *Preview) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_preview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preview.ProtoReflect.Descriptor instead.
func (*Preview) Descriptor() ([]byte, []int) {
	return file_api_v1_preview_proto_rawDescGZIP(), []int{2}
}

func (x *Preview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Preview) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Preview) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Preview) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Preview) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Preview) GetLastAccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessAt
	}
	return nil
}

func (x *Preview) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ListPreviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Previews      []*Preview             `protobuf:"bytes,1,rep,name=previews,proto3" json:"previews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPreviewsResponse) Reset() {
	*x = ListPreviewsResponse{}
	mi := &file_api_v1_preview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPreviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPreviewsResponse) ProtoMessage() {}

func (x *ListPreviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_preview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPreviewsResponse.ProtoReflect.Descriptor instead.
func (*ListPreviewsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_preview_proto_rawDescGZIP(), []int{3}
}

func (x *ListPreviewsResponse) GetPreviews() []*Preview {
	if x != nil {
		return x.Previews
	}
	return nil
}

var File_api_v1_preview_proto protoreflect.FileDescriptor

const file_api_v1_preview_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/preview.proto\x12\x0eworkpreview.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x14CreatePreviewRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"&\n" +
	"\x14DeletePreviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8f\x02\n" +
	"\aPreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\x0elast_access_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastAccessAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"K\n" +
	"\x14ListPreviewsResponse\x123\n" +
	"\bpreviews\x18\x01 \x03(\v2\x17.workpreview.v1.PreviewR\bpreviews2\xfd\x01\n" +
	"\x0ePreviewService\x12N\n" +
	"\rCreatePreview\x12$.workpreview.v1.CreatePreviewRequest\x1a\x17.workpreview.v1.Preview\x12M\n" +
	"\rDeletePreview\x12$.workpreview.v1.DeletePreviewRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fListPreviews\x12\x16.google.protobuf.Empty\x1a$.workpreview.v1.ListPreviewsResponseB7Z5github.com/connoralydon/work-preview/api/v1;previewv1b\x06proto3"

var (
	file_api_v1_preview_proto_rawDescOnce sync.Once
	file_api_v1_preview_proto_rawDescData []byte
)

func file_api_v1_preview_proto_rawDescGZIP() []byte {
	file_api_v1_preview_proto_rawDescOnce.Do(func() {
		file_api_v1_preview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_preview_proto_rawDesc), len(file_api_v1_preview_proto_rawDesc)))
	})
	return file_api_v1_preview_proto_rawDescData
}

var file_api_v1_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_preview_proto_goTypes = []any{
	(*CreatePreviewRequest)(nil),  // 0: workpreview.v1.CreatePreviewRequest
	(*DeletePreviewRequest)(nil),  // 1: workpreview.v1.DeletePreviewRequest
	(*Preview)(nil),               // 2: workpreview.v1.Preview
	(*ListPreviewsResponse)(nil),  // 3: workpreview.v1.ListPreviewsResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_api_v1_preview_proto_depIdxs = []int32{
	4, // 0: workpreview.v1.Preview.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: workpreview.v1.Preview.last_access_at:type_name -> google.protobuf.Timestamp
	4, // 2: workpreview.v1.Preview.expires_at:type_name -> google.protobuf.Timestamp
	2, // 3: workpreview.v1.ListPreviewsResponse.previews:type_name -> workpreview.v1.Preview
	0, // 4: workpreview.v1.PreviewService.CreatePreview:input_type -> workpreview.v1.CreatePreviewRequest
	1, // 5: workpreview.v1.PreviewService.DeletePreview:input_type -> workpreview.v1.DeletePreviewRequest
	5, // 6: workpreview.v1.PreviewService.ListPreviews:input_type -> google.protobuf.Empty
	2, // 7: workpreview.v1.PreviewService.CreatePreview:output_type -> workpreview.v1.Preview
	5, // 8: workpreview.v1.PreviewService.DeletePreview:output_type -> google.protobuf.Empty
	3, // 9: workpreview.v1.PreviewService.ListPreviews:output_type -> workpreview.v1.ListPreviewsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_preview_proto_init() }
func file_api_v1_preview_proto_init() {
	if File_api_v1_preview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_preview_proto_rawDesc), len(file_api_v1_preview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_preview_proto_goTypes,
		DependencyIndexes: file_api_v1_preview_proto_depIdxs,
		MessageInfos:      file_api_v1_preview_proto_msgTypes,
	}.Build()
	File_api_v1_preview_proto = out.File
	file_api_v1_preview_proto_goTypes = nil
	file_api_v1_preview_proto_depIdxs = nil
}
