// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.1
// source: api/v1/preview.proto

package previewv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreviewService_CreatePreview_FullMethodName = "/workpreview.v1.PreviewService/CreatePreview"
	PreviewService_DeletePreview_FullMethodName = "/workpreview.v1.PreviewService/DeletePreview"
	PreviewService_ListPreviews_FullMethodName  = "/workpreview.v1.PreviewService/ListPreviews"
)

// PreviewServiceClient is the client API for PreviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreviewServiceClient interface {
	CreatePreview(ctx context.Context, in *CreatePreviewRequest, opts ...grpc.CallOption) (*Preview, error)
	DeletePreview(ctx context.Context, in *DeletePreviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPreviews(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPreviewsResponse, error)
}

type previewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreviewServiceClient(cc grpc.ClientConnInterface) PreviewServiceClient {
	return &previewServiceClient{cc}
}

func (c *previewServiceClient) CreatePreview(ctx context.Context, in *CreatePreviewRequest, opts ...grpc.CallOption) (*Preview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Preview)
	err := c.cc.Invoke(ctx, PreviewService_CreatePreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *previewServiceClient) DeletePreview(ctx context.Context, in *DeletePreviewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PreviewService_DeletePreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *previewServiceClient) ListPreviews(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPreviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPreviewsResponse)
	err := c.cc.Invoke(ctx, PreviewService_ListPreviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreviewServiceServer is the server API for PreviewService service.
// All implementations must embed UnimplementedPreviewServiceServer
// for forward compatibility.
type PreviewServiceServer interface {
	CreatePreview(context.Context, *CreatePreviewRequest) (*Preview, error)
	DeletePreview(context.Context, *DeletePreviewRequest) (*emptypb.Empty, error)
	ListPreviews(context.Context, *emptypb.Empty) (*ListPreviewsResponse, error)
	mustEmbedUnimplementedPreviewServiceServer()
}

// UnimplementedPreviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreviewServiceServer struct{}

func (UnimplementedPreviewServiceServer) CreatePreview(context.Context, *CreatePreviewRequest) (*Preview, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePreview not implemented")
}
func (UnimplementedPreviewServiceServer) DeletePreview(context.Context, *DeletePreviewRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePreview not implemented")
}
func (UnimplementedPreviewServiceServer) ListPreviews(context.Context, *emptypb.Empty) (*ListPreviewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPreviews not implemented")
}
func (UnimplementedPreviewServiceServer) mustEmbedUnimplementedPreviewServiceServer() {}
func (UnimplementedPreviewServiceServer) testEmbeddedByValue()                        {}

// UnsafePreviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreviewServiceServer will
// result in compilation errors.
type UnsafePreviewServiceServer interface {
	mustEmbedUnimplementedPreviewServiceServer()
}

func RegisterPreviewServiceServer(s grpc.ServiceRegistrar, srv PreviewServiceServer) {
	// If the following call panics, it indicates UnimplementedPreviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreviewService_ServiceDesc, srv)
}

func _PreviewService_CreatePreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreviewServiceServer).CreatePreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreviewService_CreatePreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreviewServiceServer).CreatePreview(ctx, req.(*CreatePreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreviewService_DeletePreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreviewServiceServer).DeletePreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreviewService_DeletePreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreviewServiceServer).DeletePreview(ctx, req.(*DeletePreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreviewService_ListPreviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreviewServiceServer).ListPreviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreviewService_ListPreviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreviewServiceServer).ListPreviews(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PreviewService_ServiceDesc is the grpc.ServiceDesc for PreviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workpreview.v1.PreviewService",
	HandlerType: (*PreviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePreview",
			Handler:    _PreviewService_CreatePreview_Handler,
		},
		{
			MethodName: "DeletePreview",
			Handler:    _PreviewService_DeletePreview_Handler,
		},
		{
			MethodName: "ListPreviews",
			Handler:    _PreviewService_ListPreviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/preview.proto",
}
