ALTER TABLE previews ADD COLUMN repository TEXT NOT NULL DEFAULT '';
ALTER TABLE previews ADD COLUMN branch TEXT NOT NULL DEFAULT '';
ALTER TABLE previews ADD COLUMN commit_hash TEXT NOT NULL DEFAULT '';
